version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: servidor
    ports:
      - "5000:5000"
    command: ["/app/server"]
    networks:
      - rede_carregamento

  charger:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ponto_de_recarga_1
    ports:
      - "6001:6001"
    environment:
      - ID=ponto_1
      - LAT=-23.5505
      - LON=-46.6333
      - PORT=6001
    command: ["/app/charger"]
    networks:
      - rede_carregamento

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cliente
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: ["/app/client"]
    networks:
      - rede_carregamento

  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cliente1
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: ["/app/client"]
    networks:
      - rede_carregamento

networks:
  rede_carregamento:
    driver: bridge
